name: chaosmonkey
version: master
summary: resiliency tool that helps applications tolerate random instance failures
description: |
  Chaos Monkey randomly terminates virtual machine instances and containers
  that run inside of your production environment. Exposing engineers to
  failures more frequently incentivizes them to build resilient services.

grade: devel
confinement: strict

parts:
  chaosmonkey:
    source: .
    plugin: go
    go-importpath: github.com/Netflix/chaosmonkey
